# cloudbuild.yaml (UI manual run friendly)
# 目標：UI 手動 Run（預設 main）也能部署，不依賴 TAG_NAME
# 流程：no-traffic deploy（canary tag）→ smoke test(/healthz) → promote traffic to latest

substitutions:
  _SERVICE: "cicd-repo"
  _REGION: "asia-east1"

  # ✅ 不用 TAG_NAME：直接部署 latest（你 GitHub Actions main build 會推這個）
  _IMAGE: "asia-east1-docker.pkg.dev/cicd-learning-483517/cicd-learngin-registry/pancioue/cicd-repo:latest"

  # smoke test path
  _SMOKE_PATH: "/healthz"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 0) 記錄目前線上 100% 的 revision（供你需要時手動回滾用）
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: "Capture current revision"
    entrypoint: bash
    args:
      - -c
      - |
        set -e
        CURRENT_REV=$$(gcloud run services describe "${_SERVICE}" \
          --region "${_REGION}" \
          --format='value(status.traffic[0].revisionName)')
        echo "Current revision: $${CURRENT_REV}"
        echo -n "$${CURRENT_REV}" > /workspace/current_rev.txt

  # 1) no-traffic 部署新 revision，並加 canary tag 產生測試 URL
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: "Deploy (no-traffic) with canary tag"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_IMAGE}
      - --region=${_REGION}
      - --no-traffic
      - --tag=canary
      - --quiet

  # 2) 取得 canary URL
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: "Get canary URL"
    entrypoint: bash
    args:
      - -c
      - |
        set -e
        CANARY_URL=$$(gcloud run services describe "${_SERVICE}" \
          --region "${_REGION}" \
          --format='value(status.traffic[?tag=="canary"].url)')
        echo "Canary URL: ${CANARY_URL}"
        echo -n "$${CANARY_URL}" > /workspace/canary_url.txt

  # 3) Smoke test
  - name: curlimages/curl:8.5.0
    id: "Smoke test"
    entrypoint: sh
    args:
      - -c
      - |
        set -e
        CANARY_URL="$$(cat /workspace/canary_url.txt)"
        echo "Hitting: $${CANARY_URL}${_SMOKE_PATH}"
        for i in 1 2 3 4 5; do
          code="$$(curl -sS -o /dev/null -w "%{http_code}" "$${CANARY_URL}${_SMOKE_PATH}" || true)"
          echo "Attempt $$i -> HTTP $${code}"
          if [ "$${code}" = "200" ]; then exit 0; fi
          sleep 2
        done
        echo "❌ Smoke test failed"
        exit 1

  # 4) 成功才切 100% 流量到 latest revision
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: "Promote traffic to latest"
    entrypoint: gcloud
    args:
      - run
      - services
      - update-traffic
      - ${_SERVICE}
      - --region=${_REGION}
      - --to-latest
      - --quiet
