# cloudbuild.yaml (UI manual run friendly)
# 目標：UI 手動 Run（預設 main）也能部署，不依賴 TAG_NAME
# 流程：no-traffic deploy（canary tag）→ smoke test(/up) → promote traffic to latest
# ✅ 加入可選 Debug：_DEBUG_MODE=1 時才會跑「route:list」

substitutions:
  _SERVICE: "cicd-repo"
  _REGION: "asia-east1"

  # 這裡放 repo base，不要帶 tag / digest
  # 注意 Artifact Registry 是否有有設置這存放區連結到 GHCR
  _IMAGE: "asia-east1-docker.pkg.dev/cicd-learning-483517/cicd-learngin-registry/pancioue/cicd-repo"

  # smoke test path
  _SMOKE_PATH: "/up"

  # ✅ Debug 開關：手動 Run 時填 1 才會跑 route:list
  _DEBUG_MODE: "0"

availableSecrets:
  secretManager:
    - versionName: projects/897396234110/secrets/gcp-artifact-registry-ghcr-cicd-repo/versions/latest
      env: GHCR_PAT

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 0) 取得 GHCR latest digest，並組出 FINAL_IMAGE = _IMAGE@sha256:...
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: "Resolve digest from GHCR and write final image"
    entrypoint: bash
    secretEnv: ["GHCR_PAT"]
    args:
      - -c
      - |
        set -euo pipefail

        OWNER="pancioue"
        REPO="cicd-repo"
        TAG="latest"

        # ✅ 用 GitHub username + PAT 做 Basic Auth 去換 registry token
        TOKEN_JSON="$$(curl -sS \
          -u "$$OWNER:$$GHCR_PAT" \
          "https://ghcr.io/token?service=ghcr.io&scope=repository:$$OWNER/$$REPO:pull")"

        REGISTRY_TOKEN="$$(echo "$$TOKEN_JSON" | sed -n 's/.*"token"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')"

        if [ -z "$$REGISTRY_TOKEN" ]; then
          echo "❌ Failed to extract registry token from GHCR response"
          echo "$$TOKEN_JSON"
          exit 1
        fi

        # 取 manifest digest（同時印出 http code / headers 方便除錯）
        HEADERS_FILE="/workspace/manifest_headers.txt"
        HTTP_CODE="$$(curl -sS -D "$$HEADERS_FILE" -o /dev/null -w "%{http_code}" \
          -H "Authorization: Bearer $$REGISTRY_TOKEN" \
          -H "Accept: application/vnd.docker.distribution.manifest.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, application/vnd.docker.distribution.manifest.list.v2+json" \
          "https://ghcr.io/v2/$$OWNER/$$REPO/manifests/$$TAG" || true)"

        echo "Manifest HTTP status: $$HTTP_CODE"
        echo "---- manifest response headers ----"
        sed -n '1,120p' "$$HEADERS_FILE" | tr -d '\r'
        echo "----------------------------------"

        GHCR_DIGEST="$$(tr -d '\r' < "$$HEADERS_FILE" | awk -F': ' 'tolower($$1)=="docker-content-digest"{print $$2}')"

        if [ -z "$$GHCR_DIGEST" ]; then
          echo "❌ Cannot read GHCR Docker-Content-Digest"
          exit 1
        fi

        echo "✅ GHCR latest digest: $$GHCR_DIGEST"

        FINAL_IMAGE="${_IMAGE}@$$GHCR_DIGEST"
        echo "✅ Final image ref: $$FINAL_IMAGE"
        echo -n "$$FINAL_IMAGE" > /workspace/image.txt

  # 1) 記錄目前線上 100% 的 revision（供你需要時手動回滾用）
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: "Capture current revision"
    entrypoint: bash
    args:
      - -c
      - |
        set -e
        CURRENT_REV=$$(gcloud run services describe "${_SERVICE}" \
          --region "${_REGION}" \
          --format='value(status.traffic[0].revisionName)')
        echo "Current revision: $${CURRENT_REV}"
        echo -n "$${CURRENT_REV}" > /workspace/current_rev.txt

  # ✅ (可選) Debug：在 Cloud Build 直接跑 image 內的 php artisan route:list（不需要 SSH/exec）
  # 只在 _DEBUG_MODE=1 時執行，預設跳過
  - name: gcr.io/cloud-builders/docker
    id: "Debug (optional) - php artisan route:list in image"
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail

        if [ "${_DEBUG_MODE}" != "1" ]; then
          echo "Skip debug routes (set _DEBUG_MODE=1 to enable)"
          exit 0
        fi

        IMAGE="$$(cat /workspace/image.txt)"
        echo "Pull image: $$IMAGE"
        docker pull "$$IMAGE"

        echo "Run: php artisan route:list"
        docker run --rm \
          -e APP_ENV=production \
          -e APP_KEY=base64:dummykeydummykeydummykeydummykeydummykeydummy= \
          "$$IMAGE" \
          sh -lc 'cd /var/www && php artisan route:list'

  # 2) no-traffic 部署新 revision，並加 canary tag 產生測試 URL
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: "Deploy (no-traffic) with canary tag"
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        IMAGE="$$(cat /workspace/image.txt)"

        gcloud run deploy "${_SERVICE}" \
          --image="$$IMAGE" \
          --region="${_REGION}" \
          --no-traffic \
          --tag=canary \
          --quiet

  # 2.5) 部署後執行一次性 Job：php artisan route:clear
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: "Run job: php artisan route:clear"
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        IMAGE="$$(cat /workspace/image.txt)"
        JOB_NAME="php-artisan-route-clear"

        if ! gcloud run jobs describe "$$JOB_NAME" --region "${_REGION}" --format='value(metadata.name)' >/dev/null 2>&1; then
          echo "Create job: $$JOB_NAME"
          gcloud run jobs create "$$JOB_NAME" \
            --region "${_REGION}" \
            --image "$$IMAGE" \
            --command "php" \
            --args "artisan","route:clear" \
            --quiet
        else
          echo "Job exists: $$JOB_NAME"
        fi

        echo "Execute job: $$JOB_NAME"
        gcloud run jobs execute "$$JOB_NAME" \
          --region "${_REGION}" \
          --wait \
          --quiet

  # 3) 取得 service URL，並「自己組出」canary tag URL：https://canary---<service_id>.run.app
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: "Compute canary URL from service URL"
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail

        SERVICE_URL=$$(gcloud run services describe "${_SERVICE}" \
          --region "${_REGION}" \
          --format='value(status.url)')

        if [ -z "$$SERVICE_URL" ]; then
          echo "❌ Cannot get service URL"
          exit 1
        fi

        CANARY_URL="$${SERVICE_URL/https:\/\//https:\/\/canary---}"

        echo "Service URL: $$SERVICE_URL"
        echo "Canary URL:  $$CANARY_URL"
        echo -n "$$CANARY_URL" > /workspace/canary_url.txt

  # 4) Smoke test（打 canary tag URL，確保測到新 revision）
  - name: curlimages/curl:8.5.0
    id: "Smoke test"
    entrypoint: sh
    args:
      - -c
      - |
        set -e
        CANARY_URL="$$(cat /workspace/canary_url.txt)"
        echo "Hitting: $$CANARY_URL${_SMOKE_PATH}"

        for i in 1 2 3 4 5; do
          code="$$(curl -sS -o /dev/null -w "%{http_code}" "$$CANARY_URL${_SMOKE_PATH}" || true)"
          echo "Attempt $$i -> HTTP $$code"
          if [ "$$code" = "200" ]; then
            echo "✅ Smoke test passed"
            exit 0
          fi
          sleep 2
        done

        echo "❌ Smoke test failed"
        echo "Current 100% revision (rollback hint): $$(cat /workspace/current_rev.txt || true)"
        exit 1

  # 5) 成功才切 100% 流量到 latest revision
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: "Promote traffic to latest"
    entrypoint: gcloud
    args:
      - run
      - services
      - update-traffic
      - ${_SERVICE}
      - --region=${_REGION}
      - --to-latest
      - --quiet
