# cloudbuild.yaml (UI manual run friendly)
# 目標：UI 手動 Run（預設 main）也能部署，不依賴 TAG_NAME
# 流程：no-traffic deploy（canary tag）→ smoke test(/healthz) → promote traffic to latest
# ✅ 加入可選 Debug：_DEBUG_MODE=1 時才會跑「route:list」

substitutions:
  _SERVICE: "cicd-repo"
  _REGION: "asia-east1"

  # ✅ 不用 TAG_NAME：直接部署 latest（你 GitHub Actions main build 會推這個）
  _IMAGE: "asia-east1-docker.pkg.dev/cicd-learning-483517/cicd-learngin-registry/pancioue/cicd-repo:latest"

  # smoke test path
  _SMOKE_PATH: "/up"

  # ✅ Debug 開關：手動 Run 時填 1 才會跑 route:list
  _DEBUG_MODE: "0"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 0) 記錄目前線上 100% 的 revision（供你需要時手動回滾用）
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: "Capture current revision"
    entrypoint: bash
    args:
      - -c
      - |
        set -e
        CURRENT_REV=$$(gcloud run services describe "${_SERVICE}" \
          --region "${_REGION}" \
          --format='value(status.traffic[?percent==100].revisionName)')
        echo "Current revision: $${CURRENT_REV}"
        echo -n "$${CURRENT_REV}" > /workspace/current_rev.txt

  # ✅ (可選) Debug：在 Cloud Build 直接跑 image 內的 php artisan route:list（不需要 SSH/exec）
  # 只在 _DEBUG_MODE=1 時執行，預設跳過
  - name: gcr.io/cloud-builders/docker
    id: "Debug (optional) - php artisan route:list in image"
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail

        if [ "${_DEBUG_MODE}" != "1" ]; then
          echo "Skip debug routes (set _DEBUG_MODE=1 to enable)"
          exit 0
        fi

        echo "Pull image: ${_IMAGE}"
        docker pull "${_IMAGE}"

        echo "Run: php artisan route:list"
        docker run --rm \
          -e APP_ENV=production \
          -e APP_KEY=base64:dummykeydummykeydummykeydummykeydummykeydummy= \
          "${_IMAGE}" \
          sh -lc 'cd /var/www && php artisan route:list'

  # 1) no-traffic 部署新 revision，並加 canary tag 產生測試 URL
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: "Deploy (no-traffic) with canary tag"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_IMAGE}
      - --region=${_REGION}
      - --no-traffic
      - --tag=canary
      - --quiet

  # 1.5) 部署後執行一次性 Job：php artisan route:clear
  # - name: gcr.io/google.com/cloudsdktool/cloud-sdk
  #   id: "Run job: php artisan route:clear"
  #   entrypoint: bash
  #   args:
  #     - -c
  #     - |
  #       set -euo pipefail
  #       JOB_NAME="php-artisan-route-clear"

  #       if ! gcloud run jobs describe "$${JOB_NAME}" --region "${_REGION}" --format='value(metadata.name)' >/dev/null 2>&1; then
  #         echo "Create job: $${JOB_NAME}"
  #         gcloud run jobs create "$${JOB_NAME}" \
  #           --region "${_REGION}" \
  #           --image "${_IMAGE}" \
  #           --command "php" \
  #           --args "artisan","route:clear" \
  #           --quiet
  #       else
  #         echo "Job exists: $${JOB_NAME}"
  #       fi

  #       echo "Execute job: $${JOB_NAME}"
  #       gcloud run jobs execute "$${JOB_NAME}" \
  #         --region "${_REGION}" \
  #         --wait \
  #         --quiet

  # 2) 取得 service URL，並「自己組出」canary tag URL：https://canary---<service_id>.run.app
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: "Compute canary URL from service URL"
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail

        SERVICE_URL=$$(gcloud run services describe "${_SERVICE}" \
          --region "${_REGION}" \
          --format='value(status.url)')

        if [ -z "$${SERVICE_URL}" ]; then
          echo "❌ Cannot get service URL"
          exit 1
        fi

        # 將 https:// 後面插入 canary---
        CANARY_URL="$${SERVICE_URL/https:\/\//https:\/\/canary---}"

        echo "Service URL: $${SERVICE_URL}"
        echo "Canary URL:  $${CANARY_URL}"
        echo -n "$${CANARY_URL}" > /workspace/canary_url.txt

  # 3) Smoke test（打 canary tag URL，確保測到新 revision）
  - name: curlimages/curl:8.5.0
    id: "Smoke test"
    entrypoint: sh
    args:
      - -c
      - |
        set -e
        CANARY_URL="$$(cat /workspace/canary_url.txt)"
        echo "Hitting: $${CANARY_URL}${_SMOKE_PATH}"

        for i in 1 2 3 4 5; do
          code="$$(curl -sS -o /dev/null -w "%{http_code}" "$${CANARY_URL}${_SMOKE_PATH}" || true)"
          echo "Attempt $$i -> HTTP $${code}"
          if [ "$${code}" = "200" ]; then
            echo "✅ Smoke test passed"
            exit 0
          fi
          sleep 2
        done

        echo "❌ Smoke test failed"
        echo "Current 100% revision (rollback hint): $$(cat /workspace/current_rev.txt || true)"
        exit 1

  # 4) 成功才切 100% 流量到 latest revision
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: "Promote traffic to latest"
    entrypoint: gcloud
    args:
      - run
      - services
      - update-traffic
      - ${_SERVICE}
      - --region=${_REGION}
      - --to-latest
      - --quiet
